servers:
    -  
        hostname: localhost
        port: 5001
        id: 1
    -   
        hostname: localhost
        port: 5002
        id: 2
    -   
        hostname: localhost
        port: 5003
        id: 3
clients:
    -   
        hostname: localhost
        port: 5004
        id: 4
    -   
        hostname: localhost
        port: 5005
        id: 5