nodes:
    -  
        hostname: localhost
        port: 8081
        id: 1
    -   
        hostname: localhost
        port: 8082
        id: 2
    -   
        hostname: localhost
        port: 8083
        id: 3